AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5 
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
